#!/bin/sh
# postrm script for denyhosts

set -e

case "$1" in
    purge)
        rm -f /var/log/denyhosts /var/log/denyhosts.0 /var/log/denyhosts.[0-9].gz
        rm -fr /var/lib/denyhosts
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d denyhosts remove >/dev/null
fi
# End automatically added section


exit 0
