#!/bin/sh
# postinst script for denyhosts

set -e

libdir=/var/lib/denyhosts/

touch /var/log/denyhosts
chmod 640 /var/log/denyhosts
chmod 640 /etc/denyhosts.conf
test -d $libdir || mkdir $libdir
chmod 750 $libdir

# Automatically added by dh_installinit
if [ -x "/etc/init.d/denyhosts" ]; then
	update-rc.d denyhosts defaults >/dev/null
	invoke-rc.d denyhosts start || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p denyhosts /usr/share/denyhosts
fi

# End automatically added section


exit 0
