#!/bin/sh
# prerm script for denyhosts

set -e

case "$1" in
    remove|upgrade|deconfigure|failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/denyhosts" ]; then
	invoke-rc.d denyhosts stop || exit $?
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p denyhosts 
else
	dpkg -L denyhosts | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section


exit 0
